library(clustermq)
library(dplyr)
library(magrittr)

# `model_code`: String of the .stan file
# `data`: List object to be passed to Stan. In most cases this will come from
#         the configuration generated by Covidestim.
# `seedVal`: The seed for the optimizer
f <- function(model_code, data) {

  # `optimizing` comes from `rstan`, assumption is that `rstan` has already
  # been loaded.
  optimizing(
    # Compile the model on the cluster. Don't save the .dso, this guarantees
    # that it will not be reused.
    object = stan_model(verbose=T, save_dso=F, model_code=model_code),
    data = data,
    algorithm = "BFGS",
    iter = 1500, 
    verbose = T,
    as_vector = F,
  )
}

# Use ClusterMQ to connect to the cluster, compile the model, and run it.
# This function can easily be modified to perform various experiments. See
# the docs: `?clustermq::Q`. Worker logs will be found in `~/`.
run <- function(f, tests, codePath, jobs_per_worker = 4) {
  result <- Q(
    f,
    data = tests$config,
    const = list(model_code = read_file(codePath)),
    job_size = jobs_per_worker,
    log_worker = T,
    pkgs = 'rstan',
    template = list(time = jobs_per_worker * 3)
  )

  mutate(tests, result = result)
}

tests <- mutate(testset, region = "Connecticut", d = list(d)) %>% getConfigs

states <- c("New York", "Florida", "New Hampshire", "Colorado")

map(
 states,
 ~mutate(testset, region = ., d = list(getStateInputs(.)))
) %>% bind_rows %>% as_tibble %>% getConfigs -> tests2

test_results2 <- run(f, tests2, "../covidestim/inst/stan/stan_program_default.stan", jobs_per_worker = 12)
